version: 0.0
os: linux
files:
  - source: /
    destination: /opt/notredame/apps/mattermost-proxy/
    owner: nd-deploy
permissions:
  - object: /opt/notredame
    pattern: '**'
    owner: nd-deploy
    group: nd-deploy
    mode: 755
hooks:
  ApplicationStop:
    - location: bin/application-stop.sh
      timeout: 3000
      runas: nd-deploy
  ApplicationStart:
    - location: bin/application-start.sh
      timeout: 5000
      runas: nd-deploy
