version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mattermost-proxy/
permissions:
  - object: /var/www/mattermost-prox/bin
    pattern: '**'
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: bin/application-stop.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: bin/application-start.sh
      timeout: 5000
      runas: root
